server:
  port: 9090

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/xm_travel?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true

# 配置mybatis实体和xml映射
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

fileBaseUrl: http://localhost:${server.port}

alipay:
  appId: 9021000142691261
  appPrivateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDry23HpzL/dTMpKFO7koI+PXZcNnCagH8L9+IsNBdI/7nY5uVNdt/06FpEe/4zU7wqeHclW3dF9yBwZDTqXTZ8g/LEQcMLWlesMpAHRAwqnRLEouxNvULN+oZ1h74n8KJOPJB0oGfXxq5ytjhzau3d7C8gfjO9Aw+8ozG8dnXllXP8794elvaZume5053jqokujkcgAxi6eD2E7SO3kOjKp7jkaxh0mZ1wqrKcFt/B6RX7NwVUK6OC9+pgZiEehYo7in8aiTN+n4t4d7DnGDvbStzKZzh/bW7pJpLJH0JBY9jIVkdB+l5ICr5oyZ0NM/WwntPr8zD6X7LmZaACVDC1AgMBAAECggEBALqXB29nsyaOAwc9v0z+egxwrLn55o+MwXyiExtxuT9uBg5LYQc027K9L7lj+Vt6lrtxCq/IOpFmJwhpc6pGSvirna+KbqMMQbalaG4nfg02sQRj/OTjsPq4ljBpU6Pde0K4EIQJ70LEGYXzBqbm5gaogP6Qf7bBtnFLHu+JOnCKl/qMqgpl9lIkClmQZy4GNcJegZmKpknI4YgxZrqmV65HoC6n7J9fojHalittojCXGCEJAC5AoHiNEOz/jw9XiU8z8plQuDay4gx0yHKmxgHWv8iiyuljr0r14yWTOZIQNwoyeWjfu6dVK1BLpjglPGLtxjQ2wfn+y7fxJwvAtH0CgYEA/GqDINubf6oiWluc9UOCFAldIU8BwizWSyfpM1VymcPqg7PtzDXwJxhF+szuRB7549luMiEhLjWLjjg5z5fVpGIchxCojHxwOi3Mu2V+4Cx8NRwfZMdQ27jgZQO2NgQRLmWGusSzY7A5U62ZBgNMvMMGYxS1RbBdEPRvGSehbhcCgYEA7ySALOjx1dcVZYRY8T71/sLAZL+sOQmB7G88SXP/SZuwiLl8Ou/NwsVsBMVDKr9s1IyrPuwh24WZr/q8vl3RF0/jklXUlKD0YTRck5BDfQoFWIfb1WB638bOC1GQZ2vCbVybtcKDQMqbs8BN0KuxNQIFXmxyIQ0fW7GFRiFfQxMCgYEAlEdxvoSjhUyJn7D/tGiy6lhR2DZUXx/9xuqsKJbCmqenhTTWtcbdy+mLeniWY3ga7gmVnWcu2blkwOgwtc2JGGb2QTW8/cJAHz02bsOB0+juEjjyDD62Nk0VrOGQUYz0FuBXVDIm+6HTG1/4a7rWgnDCuMO6dTTUhxhAh3NrdoMCgYEAoigW/dzq9zyEFrU6dkNiHODEAszxpC9tOPxoXcpZJfl7KArWUUSAOn0R9N4p4FezHSFRkTYe8zLRdsHHsDH/cRZL0tN+dVX6v9r4l1rwWF4uJ8zf5P0p9Ili98vT5jzstqlgMEx4IbwA/k78tO1nGPGI4HEapoy2Yb+rBlXkuZ8CgYA1gkcvH8tyLjgcYT+DIcrb8M6JNuWmRuYyfrtBjCaDlT1UROK2MIiZC4uXThLGD7KO/RXneLhmDk4JIG6sw82iCxVS3cYxGzmeZRV5WtCgSxup/rgcyarsY4q+kxr/jg8BPicnj9slPlTHxpVv6yrjtD7YE/uQ5AVnsPgkWpHfTw==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8ULZVSdPq3LaqhmoppeTIQDUww3HAIt4JmG8SEuMRgmmnjJzoylSnDzS5ZeXmaCptwiO6EtjSLnpYI2ZEOwV07kbyyQDquq9SyEidzYNDhjyPPjPaf5h46SPcbrVhUfWsjltfS9qyd8R+UlXK6M6XJnfdSKnProH+2lWh7ddOzM3UuRTN94a4IivlGaCvgh3yhfWzc72fmyApactLVoF5inge0l/enK5J55XDCGhwQUIbKPIUhyZr5c964WaiDTYgJ2kmfiT6FYFpnSfsIq2YLpvgqvVR5/UYk4OZx9FfzCipeQzklIJKDHDHNfuWOO15FfoIYvq0KmRYYwFUuniywIDAQAB
  notifyUrl: http://uf2e6264.natappfree.cc/alipay/notify

aliyun:
  dashscope:
    apiKey: sk-e4e8cb67244f43bbad94ca09b8537357